[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "omni-ring"
version = "0.1.0"
description = "Coprime Resonator Hyperdimensional Engine"
license = { file = "LICENSING.md" }
dependencies = [
    "numpy>=1.20.0"
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
where = ["."]
include = ["omni_ring*"]
exclude = ["c_src*", "tests*"]

[tool.setuptools.package-data]
omni_ring = ["*.so"]
